spring:
    profiles:
        active: local
        group:
            local: local, common
            blue: blue, common
            green: green, common


server:
    env: blue

---

spring:
    config:
        activate:
            on-profile: local

server:
    port: 8080
    address: localhost

---

spring:
    config:
        activate:
            on-profile: blue

server:
    port: 8080
    address: 15.164.123.197

---

spring:
    config:
        activate:
            on-profile: green

server:
    port: 8081
    address: 15.164.123.197

---

spring:
    config:
        activate:
            on-profile: common

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/block
        username: root
        password: hk987852! #mysql 비밀 번호

    sql:
        init:
            mode: never
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                show_sql: true
                format_sql: true
                use_sql_comments: true
                hbm2ddl:
                    auto: update
